### ISSUE TITLE
Incompatible with Better Advancements

### ISSUE THREAD

**Issue by NielsPilgaard** [Buuz135/Seals#1]
Hello!

When Better Advancements is installed in the same instance as Seals, the Seals do not show up - I'm guessing the big advancement GUI is simply covering them up. Please let me know if you need any additional information.

![billede](https://user-images.githubusercontent.com/21295394/68549162-7602fe80-03f5-11ea-8292-193f3d5206e4.png)

**Comment by Buuz135** [comment]
Fixed in https://github.com/Buuz135/Seals/commit/e340b6996cd439e27069891be6a3a77912f76f9e

**Comment by NielsPilgaard** [comment]
Thanks!
