### ISSUE TITLE
Custom Seal Titles

### ISSUE THREAD

**Issue by SethCohen** [Buuz135/Seals#2]
Add the ability to create custom seal names, please.

When trying to do so myself, although its possible to create custom seals, the titles don't work and there doesn't seem to be a way to create custom titles in general. 

![image](https://user-images.githubusercontent.com/47002293/71412186-8aecc780-261a-11ea-95c2-4047016c2e51.png)
![image](https://user-images.githubusercontent.com/47002293/71412189-8fb17b80-261a-11ea-9cc3-35a2591ca4ff.png)
![image](https://user-images.githubusercontent.com/47002293/71412219-b8d20c00-261a-11ea-882a-5fdbd4d1c890.png)

**Comment by Buuz135** [comment]
You need to load a lang file with those keys
