### ISSUE TITLE
Backpacked rendering

### ISSUE THREAD

**Issue by phyne** [Buuz135/Seals#3]
Forge 1.14.4 - 28.1.113

seals-1.14.4-1.0.2
backpacked-1.2.0-1.14.4
curios-FORGE-1.14.4-1.0.6

When using [Backpacked](https://www.curseforge.com/minecraft/mc-mods/backpacked) in conjunction with [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) to place the backpack in a curios backpack slot, Seals prevents the rendering of the backpack on the players back.

**Comment by Buuz135** [comment]
1.14 not Supported
