### ISSUE TITLE
Rendering behind advancement background

### ISSUE THREAD

**Issue by Darkere** [Buuz135/Seals#4]
![image](https://user-images.githubusercontent.com/4283717/73120803-c872a680-3f72-11ea-8501-7317b1fa9bf1.png)
![image](https://user-images.githubusercontent.com/4283717/73120805-cc062d80-3f72-11ea-9a97-8b117013fdba.png)

Forge: 30.0.43
seals-1.15.1-1.1.0

**Comment by forthwist** [comment]
Can confirm, having same issue.  Would love to see this fixed, Seals is such a great little mod.

**Comment by Buuz135** [comment]
Should be fixed
